export const avatars = [
  {
    id: 0,
    img: require('../../assets/avatars/Default.png'),
  },
  {
    id: 1,
    img: require('../../assets/avatars/Beach_Chairs.png'),
  },
  { id: 2, img: require('../../assets/avatars/Chess_Pieces.png') },
  { id: 3, img: require('../../assets/avatars/Dirt_Bike.png') },
  { id: 4, img: require('../../assets/avatars/Friendly_Dog.png') },
  { id: 5, img: require('../../assets/avatars/Orange_Daisy.png') },
  { id: 6, img: require('../../assets/avatars/Palm_Trees.png') },
  { id: 7, img: require('../../assets/avatars/Rocket_Launch.png') },
  { id: 8, img: require('../../assets/avatars/Rubber_Ducky.png') },
  { id: 9, img: require('../../assets/avatars/Running_Horses.png') },
  { id: 10, img: require('../../assets/avatars/Skateboarder.png') },
  { id: 11, img: require('../../assets/avatars/Soccer_Ball.png') },
];

export const heroBannerColors = [
  {
    id: 0,
    color: '#cba3ff',
  },
  {
    id: 1,
    color: '#7ac0d4',
  },
  {
    id: 2,
    color: '#20a5d8',
  },

  { id: 3, color: '#a8e6cf' },
  { id: 4, color: '#ffd3b6' },
  { id: 5, color: '#ffaaa5' },
  { id: 6, color: '#ff8b94' },
  {
    id: 7,
    color: '#4b3832',
  },
  {
    id: 8,
    color: '#854442',
  },
  {
    id: 9,
    color: '#451e3e',
  },
  {
    id: 10,
    color: '#3d1e6d',
  },
  {
    id: 11,
    color: '#851e3e',
  },
];

export const blankContact = {
  id: 0,
  firstName: '',
  lastName: '',
  phones: [
    {
      number: '',
      callCode: '+33',
    },
  ],
  email: '',
  image: 0,
  favorite: false,
  notes: '',
  color: 0,
};

export const callingCodes = [
  { alpha: 'CA', emoji: '🇨🇦', callCode: '+1', name: 'Canada' },
  {
    alpha: 'UM',
    emoji: '🇺🇲',
    callCode: '+1',
    name: 'United States Minor Outlying Islands',
  },
  { alpha: 'US', emoji: '🇺🇸', callCode: '+1', name: 'United States' },
  { alpha: 'KZ', emoji: '🇰🇿', callCode: '+7', name: 'Kazakhstan' },
  {
    alpha: 'RU',
    emoji: '🇷🇺',
    callCode: '+7',
    name: 'Russian Federation',
  },
  { alpha: 'EG', emoji: '🇪🇬', callCode: '+20', name: 'Egypt' },
  { alpha: 'ZA', emoji: '🇿🇦', callCode: '+27', name: 'South Africa' },
  { alpha: 'GR', emoji: '🇬🇷', callCode: '+30', name: 'Greece' },
  { alpha: 'NL', emoji: '🇳🇱', callCode: '+31', name: 'Netherlands' },
  { alpha: 'BE', emoji: '🇧🇪', callCode: '+32', name: 'Belgium' },
  { alpha: 'FR', emoji: '🇫🇷', callCode: '+33', name: 'France' },
  { alpha: 'ES', emoji: '🇪🇸', callCode: '+34', name: 'Spain' },
  { alpha: 'HU', emoji: '🇭🇺', callCode: '+36', name: 'Hungary' },
  { alpha: 'IT', emoji: '🇮🇹', callCode: '+39', name: 'Italy' },
  { alpha: 'RO', emoji: '🇷🇴', callCode: '+40', name: 'Romania' },
  { alpha: 'CH', emoji: '🇨🇭', callCode: '+41', name: 'Switzerland' },
  { alpha: 'AT', emoji: '🇦🇹', callCode: '+43', name: 'Austria' },
  {
    alpha: 'GB',
    emoji: '🇬🇧',
    callCode: '+44',
    name: 'United Kingdom',
  },
  { alpha: 'GG', emoji: '🇬🇬', callCode: '+44', name: 'Guernsey' },
  { alpha: 'IM', emoji: '🇮🇲', callCode: '+44', name: 'Isle Of Man' },
  { alpha: 'JE', emoji: '🇯🇪', callCode: '+44', name: 'Jersey' },
  { alpha: 'DK', emoji: '🇩🇰', callCode: '+45', name: 'Denmark' },
  { alpha: 'SE', emoji: '🇸🇪', callCode: '+46', name: 'Sweden' },
  { alpha: 'NO', emoji: '🇳🇴', callCode: '+47', name: 'Norway' },
  {
    alpha: 'SJ',
    emoji: '🇸🇯',
    callCode: '+47',
    name: 'Svalbard And Jan Mayen',
  },
  { alpha: 'PL', emoji: '🇵🇱', callCode: '+48', name: 'Poland' },
  { alpha: 'DE', emoji: '🇩🇪', callCode: '+49', name: 'Germany' },
  { alpha: 'PE', emoji: '🇵🇪', callCode: '+51', name: 'Peru' },
  { alpha: 'MX', emoji: '🇲🇽', callCode: '+52', name: 'Mexico' },
  { alpha: 'CU', emoji: '🇨🇺', callCode: '+53', name: 'Cuba' },
  { alpha: 'AR', emoji: '🇦🇷', callCode: '+54', name: 'Argentina' },
  { alpha: 'BR', emoji: '🇧🇷', callCode: '+55', name: 'Brazil' },
  { alpha: 'CL', emoji: '🇨🇱', callCode: '+56', name: 'Chile' },
  { alpha: 'CO', emoji: '🇨🇴', callCode: '+57', name: 'Colombia' },
  {
    alpha: 'VE',
    emoji: '🇻🇪',
    callCode: '+58',
    name: 'Venezuela, Bolivarian Republic Of',
  },
  { alpha: 'MY', emoji: '🇲🇾', callCode: '+60', name: 'Malaysia' },
  { alpha: 'AU', emoji: '🇦🇺', callCode: '+61', name: 'Australia' },
  {
    alpha: 'CC',
    emoji: '🇨🇨',
    callCode: '+61',
    name: 'Cocos (Keeling) Islands',
  },
  {
    alpha: 'CX',
    emoji: '🇨🇽',
    callCode: '+61',
    name: 'Christmas Island',
  },
  { alpha: 'ID', emoji: '🇮🇩', callCode: '+62', name: 'Indonesia' },
  { alpha: 'PH', emoji: '🇵🇭', callCode: '+63', name: 'Philippines' },
  { alpha: 'NZ', emoji: '🇳🇿', callCode: '+64', name: 'New Zealand' },
  { alpha: 'SG', emoji: '🇸🇬', callCode: '+65', name: 'Singapore' },
  { alpha: 'TH', emoji: '🇹🇭', callCode: '+66', name: 'Thailand' },
  { alpha: 'JP', emoji: '🇯🇵', callCode: '+81', name: 'Japan' },
  {
    alpha: 'KR',
    emoji: '🇰🇷',
    callCode: '+82',
    name: 'Korea, Republic Of',
  },
  { alpha: 'VN', emoji: '🇻🇳', callCode: '+84', name: 'Viet Nam' },
  { alpha: 'CN', emoji: '🇨🇳', callCode: '+86', name: 'China' },
  { alpha: 'TR', emoji: '🇹🇷', callCode: '+90', name: 'Turkey' },
  { alpha: 'IN', emoji: '🇮🇳', callCode: '+91', name: 'India' },
  { alpha: 'PK', emoji: '🇵🇰', callCode: '+92', name: 'Pakistan' },
  { alpha: 'AF', emoji: '🇦🇫', callCode: '+93', name: 'Afghanistan' },
  { alpha: 'LK', emoji: '🇱🇰', callCode: '+94', name: 'Sri Lanka' },
  { alpha: 'MM', emoji: '🇲🇲', callCode: '+95', name: 'Myanmar' },
  {
    alpha: 'IR',
    emoji: '🇮🇷',
    callCode: '+98',
    name: 'Iran, Islamic Republic Of',
  },
  { alpha: 'SS', emoji: '🇸🇸', callCode: '+211', name: 'South Sudan' },
  {
    alpha: 'EH',
    emoji: '🇪🇭',
    callCode: '+212',
    name: 'Western Sahara',
  },
  { alpha: 'MA', emoji: '🇲🇦', callCode: '+212', name: 'Morocco' },
  { alpha: 'DZ', emoji: '🇩🇿', callCode: '+213', name: 'Algeria' },
  { alpha: 'TN', emoji: '🇹🇳', callCode: '+216', name: 'Tunisia' },
  { alpha: 'LY', emoji: '🇱🇾', callCode: '+218', name: 'Libya' },
  { alpha: 'GM', emoji: '🇬🇲', callCode: '+220', name: 'Gambia' },
  { alpha: 'SN', emoji: '🇸🇳', callCode: '+221', name: 'Senegal' },
  { alpha: 'MR', emoji: '🇲🇷', callCode: '+222', name: 'Mauritania' },
  { alpha: 'ML', emoji: '🇲🇱', callCode: '+223', name: 'Mali' },
  { alpha: 'GN', emoji: '🇬🇳', callCode: '+224', name: 'Guinea' },
  {
    alpha: 'CI',
    emoji: '🇨🇮',
    callCode: '+225',
    name: "Côte d'Ivoire",
  },
  {
    alpha: 'BF',
    emoji: '🇧🇫',
    callCode: '+226',
    name: 'Burkina Faso',
  },
  { alpha: 'NE', emoji: '🇳🇪', callCode: '+227', name: 'Niger' },
  { alpha: 'TG', emoji: '🇹🇬', callCode: '+228', name: 'Togo' },
  { alpha: 'BJ', emoji: '🇧🇯', callCode: '+229', name: 'Benin' },
  { alpha: 'MU', emoji: '🇲🇺', callCode: '+230', name: 'Mauritius' },
  { alpha: 'LR', emoji: '🇱🇷', callCode: '+231', name: 'Liberia' },
  {
    alpha: 'SL',
    emoji: '🇸🇱',
    callCode: '+232',
    name: 'Sierra Leone',
  },
  { alpha: 'GH', emoji: '🇬🇭', callCode: '+233', name: 'Ghana' },
  { alpha: 'NG', emoji: '🇳🇬', callCode: '+234', name: 'Nigeria' },
  { alpha: 'TD', emoji: '🇹🇩', callCode: '+235', name: 'Chad' },
  {
    alpha: 'CF',
    emoji: '🇨🇫',
    callCode: '+236',
    name: 'Central African Republic',
  },
  { alpha: 'CM', emoji: '🇨🇲', callCode: '+237', name: 'Cameroon' },
  { alpha: 'CV', emoji: '🇨🇻', callCode: '+238', name: 'Cabo Verde' },
  {
    alpha: 'ST',
    emoji: '🇸🇹',
    callCode: '+239',
    name: 'Sao Tome and Principe',
  },
  {
    alpha: 'GQ',
    emoji: '🇬🇶',
    callCode: '+240',
    name: 'Equatorial Guinea',
  },
  {
    alpha: 'FX',
    emoji: '',
    callCode: '+241',
    name: 'France, Metropolitan',
  },
  { alpha: 'GA', emoji: '🇬🇦', callCode: '+241', name: 'Gabon' },
  {
    alpha: 'CG',
    emoji: '🇨🇬',
    callCode: '+242',
    name: 'Republic Of Congo',
  },
  {
    alpha: 'CD',
    emoji: '🇨🇩',
    callCode: '+243',
    name: 'Democratic Republic Of Congo',
  },
  { alpha: 'AO', emoji: '🇦🇴', callCode: '+244', name: 'Angola' },
  {
    alpha: 'GW',
    emoji: '🇬🇼',
    callCode: '+245',
    name: 'Guinea-bissau',
  },
  {
    alpha: 'IO',
    emoji: '🇮🇴',
    callCode: '+246',
    name: 'British Indian Ocean Territory',
  },
  {
    alpha: 'AC',
    emoji: '',
    callCode: '+247',
    name: 'Ascension Island',
  },
  { alpha: 'SC', emoji: '🇸🇨', callCode: '+248', name: 'Seychelles' },
  { alpha: 'SD', emoji: '🇸🇩', callCode: '+249', name: 'Sudan' },
  { alpha: 'RW', emoji: '🇷🇼', callCode: '+250', name: 'Rwanda' },
  { alpha: 'ET', emoji: '🇪🇹', callCode: '+251', name: 'Ethiopia' },
  { alpha: 'SO', emoji: '🇸🇴', callCode: '+252', name: 'Somalia' },
  { alpha: 'DJ', emoji: '🇩🇯', callCode: '+253', name: 'Djibouti' },
  { alpha: 'KE', emoji: '🇰🇪', callCode: '+254', name: 'Kenya' },
  {
    alpha: 'TZ',
    emoji: '🇹🇿',
    callCode: '+255',
    name: 'Tanzania, United Republic Of',
  },
  { alpha: 'UG', emoji: '🇺🇬', callCode: '+256', name: 'Uganda' },
  { alpha: 'BI', emoji: '🇧🇮', callCode: '+257', name: 'Burundi' },
  { alpha: 'MZ', emoji: '🇲🇿', callCode: '+258', name: 'Mozambique' },
  { alpha: 'ZM', emoji: '🇿🇲', callCode: '+260', name: 'Zambia' },
  { alpha: 'MG', emoji: '🇲🇬', callCode: '+261', name: 'Madagascar' },
  { alpha: 'RE', emoji: '🇷🇪', callCode: '+262', name: 'Reunion' },
  { alpha: 'YT', emoji: '🇾🇹', callCode: '+262', name: 'Mayotte' },
  { alpha: 'ZW', emoji: '🇿🇼', callCode: '+263', name: 'Zimbabwe' },
  { alpha: 'NA', emoji: '🇳🇦', callCode: '+264', name: 'Namibia' },
  { alpha: 'MW', emoji: '🇲🇼', callCode: '+265', name: 'Malawi' },
  { alpha: 'LS', emoji: '🇱🇸', callCode: '+266', name: 'Lesotho' },
  { alpha: 'BW', emoji: '🇧🇼', callCode: '+267', name: 'Botswana' },
  { alpha: 'SZ', emoji: '🇸🇿', callCode: '+268', name: 'Swaziland' },
  { alpha: 'KM', emoji: '🇰🇲', callCode: '+269', name: 'Comoros' },
  {
    alpha: 'SH',
    emoji: '🇸🇭',
    callCode: '+290',
    name: 'Saint Helena, Ascension And Tristan Da Cunha',
  },
  {
    alpha: 'TA',
    emoji: '',
    callCode: '+290',
    name: 'Tristan de Cunha',
  },
  { alpha: 'ER', emoji: '🇪🇷', callCode: '+291', name: 'Eritrea' },
  { alpha: 'AW', emoji: '🇦🇼', callCode: '+297', name: 'Aruba' },
  {
    alpha: 'FO',
    emoji: '🇫🇴',
    callCode: '+298',
    name: 'Faroe Islands',
  },
  { alpha: 'GL', emoji: '🇬🇱', callCode: '+299', name: 'Greenland' },
  { alpha: 'GI', emoji: '🇬🇮', callCode: '+350', name: 'Gibraltar' },
  { alpha: 'PT', emoji: '🇵🇹', callCode: '+351', name: 'Portugal' },
  { alpha: 'LU', emoji: '🇱🇺', callCode: '+352', name: 'Luxembourg' },
  { alpha: 'IE', emoji: '🇮🇪', callCode: '+353', name: 'Ireland' },
  { alpha: 'IS', emoji: '🇮🇸', callCode: '+354', name: 'Iceland' },
  { alpha: 'AL', emoji: '🇦🇱', callCode: '+355', name: 'Albania' },
  { alpha: 'MT', emoji: '🇲🇹', callCode: '+356', name: 'Malta' },
  { alpha: 'CY', emoji: '🇨🇾', callCode: '+357', name: 'Cyprus' },
  {
    alpha: 'AX',
    emoji: '🇦🇽',
    callCode: '+358',
    name: 'Åland Islands',
  },
  { alpha: 'FI', emoji: '🇫🇮', callCode: '+358', name: 'Finland' },
  { alpha: 'BG', emoji: '🇧🇬', callCode: '+359', name: 'Bulgaria' },
  { alpha: 'LT', emoji: '🇱🇹', callCode: '+370', name: 'Lithuania' },
  { alpha: 'LV', emoji: '🇱🇻', callCode: '+371', name: 'Latvia' },
  { alpha: 'EE', emoji: '🇪🇪', callCode: '+372', name: 'Estonia' },
  { alpha: 'MD', emoji: '🇲🇩', callCode: '+373', name: 'Moldova' },
  { alpha: 'AM', emoji: '🇦🇲', callCode: '+374', name: 'Armenia' },
  { alpha: 'BY', emoji: '🇧🇾', callCode: '+375', name: 'Belarus' },
  { alpha: 'AD', emoji: '🇦🇩', callCode: '+376', name: 'Andorra' },
  { alpha: 'MC', emoji: '🇲🇨', callCode: '+377', name: 'Monaco' },
  { alpha: 'SM', emoji: '🇸🇲', callCode: '+378', name: 'San Marino' },
  {
    alpha: 'VA',
    emoji: '🇻🇦',
    callCode: '+379',
    name: 'Vatican City State',
  },
  { alpha: 'UA', emoji: '🇺🇦', callCode: '+380', name: 'Ukraine' },
  { alpha: 'RS', emoji: '🇷🇸', callCode: '+381', name: 'Serbia' },
  { alpha: 'ME', emoji: '🇲🇪', callCode: '+382', name: 'Montenegro' },
  { alpha: 'XK', emoji: '', callCode: '+383', name: 'Kosovo' },
  { alpha: 'HR', emoji: '🇭🇷', callCode: '+385', name: 'Croatia' },
  { alpha: 'SI', emoji: '🇸🇮', callCode: '+386', name: 'Slovenia' },
  {
    alpha: 'BA',
    emoji: '🇧🇦',
    callCode: '+387',
    name: 'Bosnia & Herzegovina',
  },
  {
    alpha: 'EU',
    emoji: '🇪🇺',
    callCode: '+388',
    name: 'European Union',
  },
  {
    alpha: 'MK',
    emoji: '🇲🇰',
    callCode: '+389',
    name: 'Macedonia, The Former Yugoslav Republic Of',
  },
  {
    alpha: 'CZ',
    emoji: '🇨🇿',
    callCode: '+420',
    name: 'Czech Republic',
  },
  { alpha: 'SK', emoji: '🇸🇰', callCode: '+421', name: 'Slovakia' },
  {
    alpha: 'LI',
    emoji: '🇱🇮',
    callCode: '+423',
    name: 'Liechtenstein',
  },
  { alpha: 'GD', emoji: '🇬🇩', callCode: '+473', name: 'Grenada' },
  {
    alpha: 'FK',
    emoji: '🇫🇰',
    callCode: '+500',
    name: 'Falkland Islands',
  },
  { alpha: 'BZ', emoji: '🇧🇿', callCode: '+501', name: 'Belize' },
  { alpha: 'GT', emoji: '🇬🇹', callCode: '+502', name: 'Guatemala' },
  { alpha: 'SV', emoji: '🇸🇻', callCode: '+503', name: 'El Salvador' },
  { alpha: 'HN', emoji: '🇭🇳', callCode: '+504', name: 'Honduras' },
  { alpha: 'NI', emoji: '🇳🇮', callCode: '+505', name: 'Nicaragua' },
  { alpha: 'CR', emoji: '🇨🇷', callCode: '+506', name: 'Costa Rica' },
  { alpha: 'PA', emoji: '🇵🇦', callCode: '+507', name: 'Panama' },
  {
    alpha: 'PM',
    emoji: '🇵🇲',
    callCode: '+508',
    name: 'Saint Pierre And Miquelon',
  },
  { alpha: 'HT', emoji: '🇭🇹', callCode: '+509', name: 'Haiti' },
  {
    alpha: 'BL',
    emoji: '🇧🇱',
    callCode: '+590',
    name: 'Saint Barthélemy',
  },
  { alpha: 'GP', emoji: '🇬🇵', callCode: '+590', name: 'Guadeloupe' },
  {
    alpha: 'MF',
    emoji: '🇲🇫',
    callCode: '+590',
    name: 'Saint Martin',
  },
  {
    alpha: 'BO',
    emoji: '🇧🇴',
    callCode: '+591',
    name: 'Bolivia, Plurinational State Of',
  },
  { alpha: 'GY', emoji: '🇬🇾', callCode: '+592', name: 'Guyana' },
  { alpha: 'EC', emoji: '🇪🇨', callCode: '+593', name: 'Ecuador' },
  {
    alpha: 'GF',
    emoji: '🇬🇫',
    callCode: '+594',
    name: 'French Guiana',
  },
  { alpha: 'PY', emoji: '🇵🇾', callCode: '+595', name: 'Paraguay' },
  { alpha: 'MQ', emoji: '🇲🇶', callCode: '+596', name: 'Martinique' },
  { alpha: 'SR', emoji: '🇸🇷', callCode: '+597', name: 'Suriname' },
  { alpha: 'UY', emoji: '🇺🇾', callCode: '+598', name: 'Uruguay' },
  {
    alpha: 'BQ',
    emoji: '🇧🇶',
    callCode: '+599',
    name: 'Bonaire, Saint Eustatius And Saba',
  },
  { alpha: 'CW', emoji: '🇨🇼', callCode: '+599', name: 'Curacao' },
  {
    alpha: 'TL',
    emoji: '🇹🇱',
    callCode: '+670',
    name: 'Timor-Leste, Democratic Republic of',
  },
  { alpha: 'AQ', emoji: '🇦🇶', callCode: '+672', name: 'Antarctica' },
  {
    alpha: 'NF',
    emoji: '🇳🇫',
    callCode: '+672',
    name: 'Norfolk Island',
  },
  {
    alpha: 'BN',
    emoji: '🇧🇳',
    callCode: '+673',
    name: 'Brunei Darussalam',
  },
  { alpha: 'NR', emoji: '🇳🇷', callCode: '+674', name: 'Nauru' },
  {
    alpha: 'PG',
    emoji: '🇵🇬',
    callCode: '+675',
    name: 'Papua New Guinea',
  },
  { alpha: 'TO', emoji: '🇹🇴', callCode: '+676', name: 'Tonga' },
  {
    alpha: 'SB',
    emoji: '🇸🇧',
    callCode: '+677',
    name: 'Solomon Islands',
  },
  { alpha: 'VU', emoji: '🇻🇺', callCode: '+678', name: 'Vanuatu' },
  { alpha: 'FJ', emoji: '🇫🇯', callCode: '+679', name: 'Fiji' },
  { alpha: 'PW', emoji: '🇵🇼', callCode: '+680', name: 'Palau' },
  {
    alpha: 'WF',
    emoji: '🇼🇫',
    callCode: '+681',
    name: 'Wallis And Futuna',
  },
  {
    alpha: 'CK',
    emoji: '🇨🇰',
    callCode: '+682',
    name: 'Cook Islands',
  },
  { alpha: 'NU', emoji: '🇳🇺', callCode: '+683', name: 'Niue' },
  { alpha: 'WS', emoji: '🇼🇸', callCode: '+685', name: 'Samoa' },
  { alpha: 'KI', emoji: '🇰🇮', callCode: '+686', name: 'Kiribati' },
  {
    alpha: 'NC',
    emoji: '🇳🇨',
    callCode: '+687',
    name: 'New Caledonia',
  },
  { alpha: 'TV', emoji: '🇹🇻', callCode: '+688', name: 'Tuvalu' },
  {
    alpha: 'PF',
    emoji: '🇵🇫',
    callCode: '+689',
    name: 'French Polynesia',
  },
  { alpha: 'TK', emoji: '🇹🇰', callCode: '+690', name: 'Tokelau' },
  {
    alpha: 'FM',
    emoji: '🇫🇲',
    callCode: '+691',
    name: 'Micronesia, Federated States Of',
  },
  {
    alpha: 'MH',
    emoji: '🇲🇭',
    callCode: '+692',
    name: 'Marshall Islands',
  },
  {
    alpha: 'KP',
    emoji: '🇰🇵',
    callCode: '+850',
    name: "Korea, Democratic People's Republic Of",
  },
  { alpha: 'HK', emoji: '🇭🇰', callCode: '+852', name: 'Hong Kong' },
  { alpha: 'MO', emoji: '🇲🇴', callCode: '+853', name: 'Macao' },
  { alpha: 'KH', emoji: '🇰🇭', callCode: '+855', name: 'Cambodia' },
  {
    alpha: 'LA',
    emoji: '🇱🇦',
    callCode: '+856',
    name: "Lao People's Democratic Republic",
  },
  { alpha: 'PN', emoji: '🇵🇳', callCode: '+872', name: 'Pitcairn' },
  { alpha: 'BD', emoji: '🇧🇩', callCode: '+880', name: 'Bangladesh' },
  { alpha: 'TW', emoji: '🇹🇼', callCode: '+886', name: 'Taiwan' },
  { alpha: 'MV', emoji: '🇲🇻', callCode: '+960', name: 'Maldives' },
  { alpha: 'LB', emoji: '🇱🇧', callCode: '+961', name: 'Lebanon' },
  { alpha: 'JO', emoji: '🇯🇴', callCode: '+962', name: 'Jordan' },
  {
    alpha: 'SY',
    emoji: '🇸🇾',
    callCode: '+963',
    name: 'Syrian Arab Republic',
  },
  { alpha: 'IQ', emoji: '🇮🇶', callCode: '+964', name: 'Iraq' },
  { alpha: 'KW', emoji: '🇰🇼', callCode: '+965', name: 'Kuwait' },
  {
    alpha: 'SA',
    emoji: '🇸🇦',
    callCode: '+966',
    name: 'Saudi Arabia',
  },
  { alpha: 'YE', emoji: '🇾🇪', callCode: '+967', name: 'Yemen' },
  { alpha: 'OM', emoji: '🇴🇲', callCode: '+968', name: 'Oman' },
  {
    alpha: 'PS',
    emoji: '🇵🇸',
    callCode: '+970',
    name: 'Palestinian Territory, Occupied',
  },
  {
    alpha: 'AE',
    emoji: '🇦🇪',
    callCode: '+971',
    name: 'United Arab Emirates',
  },
  { alpha: 'IL', emoji: '🇮🇱', callCode: '+972', name: 'Israel' },
  { alpha: 'BH', emoji: '🇧🇭', callCode: '+973', name: 'Bahrain' },
  { alpha: 'QA', emoji: '🇶🇦', callCode: '+974', name: 'Qatar' },
  { alpha: 'BT', emoji: '🇧🇹', callCode: '+975', name: 'Bhutan' },
  { alpha: 'MN', emoji: '🇲🇳', callCode: '+976', name: 'Mongolia' },
  { alpha: 'NP', emoji: '🇳🇵', callCode: '+977', name: 'Nepal' },
  { alpha: 'TJ', emoji: '🇹🇯', callCode: '+992', name: 'Tajikistan' },
  {
    alpha: 'TM',
    emoji: '🇹🇲',
    callCode: '+993',
    name: 'Turkmenistan',
  },
  { alpha: 'AZ', emoji: '🇦🇿', callCode: '+994', name: 'Azerbaijan' },
  { alpha: 'GE', emoji: '🇬🇪', callCode: '+995', name: 'Georgia' },
  { alpha: 'KG', emoji: '🇰🇬', callCode: '+996', name: 'Kyrgyzstan' },
  { alpha: 'UZ', emoji: '🇺🇿', callCode: '+998', name: 'Uzbekistan' },
  { alpha: 'BS', emoji: '🇧🇸', callCode: '+1 242', name: 'Bahamas' },
  { alpha: 'BB', emoji: '🇧🇧', callCode: '+1 246', name: 'Barbados' },
  { alpha: 'AI', emoji: '🇦🇮', callCode: '+1 264', name: 'Anguilla' },
  {
    alpha: 'AG',
    emoji: '🇦🇬',
    callCode: '+1 268',
    name: 'Antigua And Barbuda',
  },
  {
    alpha: 'VG',
    emoji: '🇻🇬',
    callCode: '+1 284',
    name: 'Virgin Islands (British)',
  },
  {
    alpha: 'VI',
    emoji: '🇻🇮',
    callCode: '+1 340',
    name: 'Virgin Islands (US)',
  },
  {
    alpha: 'KY',
    emoji: '🇰🇾',
    callCode: '+1 345',
    name: 'Cayman Islands',
  },
  { alpha: 'BM', emoji: '🇧🇲', callCode: '+1 441', name: 'Bermuda' },
  {
    alpha: 'TC',
    emoji: '🇹🇨',
    callCode: '+1 649',
    name: 'Turks And Caicos Islands',
  },
  {
    alpha: 'MS',
    emoji: '🇲🇸',
    callCode: '+1 664',
    name: 'Montserrat',
  },
  {
    alpha: 'MP',
    emoji: '🇲🇵',
    callCode: '+1 670',
    name: 'Northern Mariana Islands',
  },
  { alpha: 'GU', emoji: '🇬🇺', callCode: '+1 671', name: 'Guam' },
  {
    alpha: 'AS',
    emoji: '🇦🇸',
    callCode: '+1 684',
    name: 'American Samoa',
  },
  {
    alpha: 'SX',
    emoji: '🇸🇽',
    callCode: '+1 721',
    name: 'Sint Maarten',
  },
  {
    alpha: 'LC',
    emoji: '🇱🇨',
    callCode: '+1 758',
    name: 'Saint Lucia',
  },
  { alpha: 'DM', emoji: '🇩🇲', callCode: '+1 767', name: 'Dominica' },
  {
    alpha: 'VC',
    emoji: '🇻🇨',
    callCode: '+1 784',
    name: 'Saint Vincent And The Grenadines',
  },
  {
    alpha: 'PR',
    emoji: '🇵🇷',
    callCode: '+1 787',
    name: 'Puerto Rico',
  },
  {
    alpha: 'DO',
    emoji: '🇩🇴',
    callCode: '+1 809',
    name: 'Dominican Republic',
  },
  {
    alpha: 'TT',
    emoji: '🇹🇹',
    callCode: '+1 868',
    name: 'Trinidad And Tobago',
  },
  {
    alpha: 'KN',
    emoji: '🇰🇳',
    callCode: '+1 869',
    name: 'Saint Kitts And Nevis',
  },
  { alpha: 'JM', emoji: '🇯🇲', callCode: '+1 876', name: 'Jamaica' },
];
